"""Render Aegis analyses to JSON and Markdown (the published LEADERBOARD.md)."""
from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

from . import analysis, registry

ROOT = Path(__file__).resolve().parents[2]
SCORING = ROOT / "scoring"
LEADERBOARD_MD = ROOT / "LEADERBOARD.md"
GENERALIZATION_SVG = ROOT / "docs" / "assets" / "generalization.svg"


def _fmt(x: float) -> str:
    return f"{x:+.2f}" if x < 0 else f"{x:.2f}"


def build_full_report(cache: analysis.ScoreCache | None = None) -> dict:
    cache = cache or analysis.ScoreCache()
    report = {
        "generated_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "scenarios": {},
    }
    for sc in registry.all_scenarios():
        rows = analysis.leaderboard(sc, cache)
        gen_rows, train, test = analysis.generalization(sc, cache)
        # co-evolve the first threshold (non-structural) family, if any
        coevo = None
        thr_family = next(
            (n for n, fam in sc.families.items() if not fam[0].structural), None
        )
        if thr_family is not None:
            c = analysis.coevolve(sc, thr_family, cache)
            coevo = {
                "family": thr_family,
                "naive": c["naive"].label,
                "naive_worstcase_saved": c["naive_worstcase_saved"],
                "coevolved": c["coevolved"].label,
                "coevolved_worstcase_saved": c["coevolved_worstcase_saved"],
                "rounds": len(c["history"]),
            }
        report["scenarios"][sc.key] = {
            "id": sc.id,
            "title": sc.title,
            "summary": sc.summary,
            "attacker_knob": sc.attacker_knob,
            "attacker_grid": sc.attacker_grid,
            "benign_total": sc.benign_total,
            "leaderboard": [asdict(r) for r in rows],
            "generalization": {
                "train": train,
                "test": test,
                "rows": [asdict(r) for r in gen_rows],
            },
            "coevolution": coevo,
        }
    return report


def write_json(report: dict, path: Path | None = None) -> Path:
    path = path or (SCORING / "leaderboard.json")
    path.write_text(json.dumps(report, indent=2))
    return path


def render_markdown(report: dict) -> str:
    out: list[str] = []
    out.append("# Aegis leaderboard\n")
    out.append(
        "> Auto-generated by `aegis bench` — every number below is produced by "
        "contract execution on the EVM (Foundry), not by a Python heuristic. "
        "Regenerate with `cd aegis-gym && python3 -m aegis bench`.\n"
    )
    out.append(f"_Last generated: {report['generated_utc']}_\n")
    out.append(
        "**Metric.** `worst-case reward` = the minimum over the whole attacker "
        "grid of `funds_saved − false_positive_rate`. It rewards a defense only "
        "if it is precise against *every* attacker in the family — blocking "
        "everything nets zero.\n"
    )

    for key, sc in report["scenarios"].items():
        out.append(f"\n## Scenario {sc['id']} — {sc['title']}\n")
        out.append(f"{sc['summary']}\n")
        out.append(
            f"Attacker axis: `{sc['attacker_knob']}` over "
            f"`{sc['attacker_grid']}`; benign suite size {sc['benign_total']}.\n"
        )
        out.append("\n### Ranking (worst-case over the full attacker grid)\n")
        out.append("| Rank | Defense | Family | Structural | Worst-case saved | Worst-case reward | Mean saved | FP |")
        out.append("|:----:|---------|--------|:----------:|:----------------:|:-----------------:|:----------:|:--:|")
        for i, r in enumerate(sc["leaderboard"], 1):
            out.append(
                f"| {i} | {r['label']} | {r['family']} | "
                f"{'✅' if r['structural'] else '—'} | "
                f"{r['worst_case_saved']:.2f} | {_fmt(r['worst_case_reward'])} | "
                f"{r['mean_saved']:.2f} | {r['fp']}/{r['benign_total']} |"
            )

        gen = sc["generalization"]
        out.append(
            f"\n### Generalization to unseen attackers "
            f"(train `{gen['train']}` → test `{gen['test']}`)\n"
        )
        out.append("| Family | Trained config | Train | Test | Gap | Verdict |")
        out.append("|--------|----------------|:-----:|:----:|:---:|---------|")
        for r in gen["rows"]:
            verdict = "generalizes" if abs(r["gap"]) < 1e-9 else "**overfits**"
            out.append(
                f"| {r['family']} | {r['trained_label']} | {_fmt(r['train'])} | "
                f"{_fmt(r['test'])} | {_fmt(r['gap'])} | {verdict} |"
            )

        co = sc.get("coevolution")
        if co:
            out.append(
                f"\n**Co-evolution ({co['family']}, {co['rounds']} rounds).** "
                f"A defender tuned only on the fast attacker — {co['naive']} — saves "
                f"**{co['naive_worstcase_saved']:.2f}** worst-case over the full grid; "
                f"the co-evolved defender — {co['coevolved']} — saves "
                f"**{co['coevolved_worstcase_saved']:.2f}**.\n"
            )

    out.append(
        "\n---\n*Structural defenses enforce an invariant that holds regardless "
        "of the attacker's parameters, so they transfer to unseen attackers "
        "(gap ≈ 0). Threshold/rate defenses fit a boundary to the attackers they "
        "were tuned on and collapse on held-out ones (gap ≈ 1).*\n"
    )
    return "\n".join(out)


def write_markdown(report: dict, path: Path | None = None) -> Path:
    path = path or LEADERBOARD_MD
    path.write_text(render_markdown(report))
    return path


# --------------------------------------------------------------------------- #
# Data-driven results chart (committed SVG, embedded in the README)
# --------------------------------------------------------------------------- #
def render_generalization_svg(report: dict) -> str:
    """A grouped bar chart of test (held-out) worst-case reward per scenario.

    For each scenario it draws the best threshold family beside the structural
    family, both evaluated on UNSEEN attackers — visualizing the headline:
    structural defenses hold (~1.0) while threshold defenses collapse (~0.0).
    """
    scenarios = report["scenarios"]
    n = len(scenarios)
    pad_l, pad_t = 60, 70
    group_w, gap = 170, 24
    plot_h = 200
    width = pad_l + n * group_w + 40
    height = pad_t + plot_h + 80
    bg, fg, muted = "#0d1117", "#e6edf3", "#8b949e"
    green, red = "#3fb950", "#f85149"

    def y_of(v):  # reward in [0,1] -> y pixel
        return pad_t + plot_h - max(0.0, min(1.0, v)) * plot_h

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" font-family="ui-sans-serif, system-ui, -apple-system, '
        f'Segoe UI, Roboto, Helvetica, Arial, sans-serif">',
        f'<rect width="{width}" height="{height}" fill="{bg}"/>',
        f'<text x="{width/2}" y="28" fill="{fg}" font-size="17" font-weight="700" '
        f'text-anchor="middle">Generalization to unseen attackers</text>',
        f'<text x="{width/2}" y="48" fill="{muted}" font-size="12" text-anchor="middle">'
        f'test worst-case reward after training on a disjoint attacker set (higher is better)</text>',
    ]
    # axis gridlines at 0 / 0.5 / 1.0
    for v in (0.0, 0.5, 1.0):
        y = y_of(v)
        parts.append(
            f'<line x1="{pad_l}" y1="{y:.1f}" x2="{width-20}" y2="{y:.1f}" '
            f'stroke="#30363d" stroke-width="1"/>'
        )
        parts.append(
            f'<text x="{pad_l-8}" y="{y+4:.1f}" fill="{muted}" font-size="11" '
            f'text-anchor="end">{v:.1f}</text>'
        )

    for i, (key, sc) in enumerate(scenarios.items()):
        rows = sc["generalization"]["rows"]
        thr = max((r for r in rows if not r["structural"]), key=lambda r: r["test"], default=None)
        stru = max((r for r in rows if r["structural"]), key=lambda r: r["test"], default=None)
        gx = pad_l + i * group_w + gap
        bar_w = (group_w - 3 * gap) / 2
        for j, (row, color, lbl) in enumerate(
            [(thr, red, "threshold"), (stru, green, "structural")]
        ):
            if row is None:
                continue
            v = max(0.0, row["test"])
            x = gx + j * (bar_w + gap)
            y = y_of(v)
            h = pad_t + plot_h - y
            # a thin stub so a 0.0 bar is still visible
            if h < 2:
                h, y = 2, pad_t + plot_h - 2
            parts.append(
                f'<rect x="{x:.1f}" y="{y:.1f}" width="{bar_w:.1f}" height="{h:.1f}" '
                f'rx="3" fill="{color}"/>'
            )
            parts.append(
                f'<text x="{x+bar_w/2:.1f}" y="{y-6:.1f}" fill="{fg}" font-size="12" '
                f'font-weight="700" text-anchor="middle">{row["test"]:.2f}</text>'
            )
            parts.append(
                f'<text x="{x+bar_w/2:.1f}" y="{pad_t+plot_h+18:.1f}" fill="{muted}" '
                f'font-size="11" text-anchor="middle">{lbl}</text>'
            )
        parts.append(
            f'<text x="{gx + (group_w-gap)/2 - bar_w/2:.1f}" y="{pad_t+plot_h+40:.1f}" '
            f'fill="{fg}" font-size="12" font-weight="600" text-anchor="middle">'
            f'{sc["id"]} {key}</text>'
        )

    parts.append(
        f'<text x="{width/2}" y="{height-12}" fill="{muted}" font-size="11" '
        f'text-anchor="middle">Across four vulnerability classes, structural defenses '
        f'generalize while threshold defenses collapse on unseen attackers.</text>'
    )
    parts.append("</svg>")
    return "\n".join(parts)


def write_generalization_svg(report: dict, path: Path | None = None) -> Path:
    path = path or GENERALIZATION_SVG
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_generalization_svg(report))
    return path
