"""Render Aegis analyses to JSON and Markdown (the published LEADERBOARD.md)."""
from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

from . import analysis, registry

ROOT = Path(__file__).resolve().parents[2]
SCORING = ROOT / "scoring"
LEADERBOARD_MD = ROOT / "LEADERBOARD.md"


def _fmt(x: float) -> str:
    return f"{x:+.2f}" if x < 0 else f"{x:.2f}"


def build_full_report(cache: analysis.ScoreCache | None = None) -> dict:
    cache = cache or analysis.ScoreCache()
    report = {
        "generated_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "scenarios": {},
    }
    for sc in registry.all_scenarios():
        rows = analysis.leaderboard(sc, cache)
        gen_rows, train, test = analysis.generalization(sc, cache)
        report["scenarios"][sc.key] = {
            "id": sc.id,
            "title": sc.title,
            "summary": sc.summary,
            "attacker_knob": sc.attacker_knob,
            "attacker_grid": sc.attacker_grid,
            "benign_total": sc.benign_total,
            "leaderboard": [asdict(r) for r in rows],
            "generalization": {
                "train": train,
                "test": test,
                "rows": [asdict(r) for r in gen_rows],
            },
        }
    return report


def write_json(report: dict, path: Path | None = None) -> Path:
    path = path or (SCORING / "leaderboard.json")
    path.write_text(json.dumps(report, indent=2))
    return path


def render_markdown(report: dict) -> str:
    out: list[str] = []
    out.append("# Aegis leaderboard\n")
    out.append(
        "> Auto-generated by `aegis bench` — every number below is produced by "
        "contract execution on the EVM (Foundry), not by a Python heuristic. "
        "Regenerate with `cd aegis-gym && python3 -m aegis bench`.\n"
    )
    out.append(f"_Last generated: {report['generated_utc']}_\n")
    out.append(
        "**Metric.** `worst-case reward` = the minimum over the whole attacker "
        "grid of `funds_saved − false_positive_rate`. It rewards a defense only "
        "if it is precise against *every* attacker in the family — blocking "
        "everything nets zero.\n"
    )

    for key, sc in report["scenarios"].items():
        out.append(f"\n## Scenario {sc['id']} — {sc['title']}\n")
        out.append(f"{sc['summary']}\n")
        out.append(
            f"Attacker axis: `{sc['attacker_knob']}` over "
            f"`{sc['attacker_grid']}`; benign suite size {sc['benign_total']}.\n"
        )
        out.append("\n### Ranking (worst-case over the full attacker grid)\n")
        out.append("| Rank | Defense | Family | Structural | Worst-case saved | Worst-case reward | Mean saved | FP |")
        out.append("|:----:|---------|--------|:----------:|:----------------:|:-----------------:|:----------:|:--:|")
        for i, r in enumerate(sc["leaderboard"], 1):
            out.append(
                f"| {i} | {r['label']} | {r['family']} | "
                f"{'✅' if r['structural'] else '—'} | "
                f"{r['worst_case_saved']:.2f} | {_fmt(r['worst_case_reward'])} | "
                f"{r['mean_saved']:.2f} | {r['fp']}/{r['benign_total']} |"
            )

        gen = sc["generalization"]
        out.append(
            f"\n### Generalization to unseen attackers "
            f"(train `{gen['train']}` → test `{gen['test']}`)\n"
        )
        out.append("| Family | Trained config | Train | Test | Gap | Verdict |")
        out.append("|--------|----------------|:-----:|:----:|:---:|---------|")
        for r in gen["rows"]:
            verdict = "generalizes" if abs(r["gap"]) < 1e-9 else "**overfits**"
            out.append(
                f"| {r['family']} | {r['trained_label']} | {_fmt(r['train'])} | "
                f"{_fmt(r['test'])} | {_fmt(r['gap'])} | {verdict} |"
            )

    out.append(
        "\n---\n*Structural defenses enforce an invariant that holds regardless "
        "of the attacker's parameters, so they transfer to unseen attackers "
        "(gap ≈ 0). Threshold/rate defenses fit a boundary to the attackers they "
        "were tuned on and collapse on held-out ones (gap ≈ 1).*\n"
    )
    return "\n".join(out)


def write_markdown(report: dict, path: Path | None = None) -> Path:
    path = path or LEADERBOARD_MD
    path.write_text(render_markdown(report))
    return path
